### ISSUE TITLE
자바스크립트의 랜덤함수는 충분히 랜덤한지 테스트하는 방법이 있는가?

### ISSUE THREAD

**Issue by oloslanrete** [oloslanrete/Texas_hold-em#1]
충분히 랜덤하다는건 정확히 어떤 의미인가? math.random()를 여러번 실행했을 때 0과 1(exculsive)사이에서 완벽히 고른 분포를 해야한다는 뜻인가?

**Comment by yoonkwon** [comment]
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Math/random

> Math.random()은 암호학적으로 안전한 난수를 제공하지 않으므로, 보안과 관련된 어떤 것에도 이 함수를 사용해서는 안 된다. 그 대신 Web Crypto API의 window.crypto.getRandomValues() 메소드를 이용하여야 한다.
