### ISSUE TITLE
유저 치팅 이슈

### ISSUE THREAD

**Issue by yoonkwon** [oloslanrete/Texas_hold-em#14]
클라이언트 정보가 console에서 접근이 되어서 값을 조작 할수 있습니다 어떻게 해결할수 있을지 고민해 봅시다.

**Comment by yoonkwon** [comment]
https://hm-x315420.slack.com/archives/C021UHGCN6A/p1622207988010100?thread_ts=1622204895.005900&cid=C021UHGCN6A

**Comment by yoonkwon** [comment]
![포커](https://user-images.githubusercontent.com/14030407/119991534-86dd8a00-c004-11eb-8cf9-f6efdebd3952.JPG)

**Comment by oloslanrete** [comment]
조사해본 결과 자바스크립트를 클라이언트쪽에서 조작하는것을 원천적으로 막을 방법은 없는것 같습니다.
그나마 소스코드를 난독화하여 조작 난이도를 높이는 것이 도움이 될것 같습니다.
클로저를 사용하면 프라이빗 메소드를 구현할 수 있다고 합니다. (https://developer.mozilla.org/ko/docs/Web/JavaScript/Closures#%ED%81%B4%EB%A1%9C%EC%A0%80%EB%A5%BC_%EC%9D%B4%EC%9A%A9%ED%95%B4%EC%84%9C_%ED%94%84%EB%9D%BC%EC%9D%B4%EB%B9%97_%EB%A9%94%EC%86%8C%EB%93%9C_private_method_%ED%9D%89%EB%82%B4%EB%82%B4%EA%B8%B0)
이 방법이 악의적인 목적을 가진 클라이언트를 막는데 도움이 될지는 잘 모르겠습니다. 콘솔에서 직접 접근을 막을 수 있을지는 몰라도 자바스크립트 소스를 복사해서 플레이어의 초기 자금을 99999로 변조해서 실행하는 방법 등이 있기 때문입니다.

**Comment by yoonkwon** [comment]
난독화와 익명함수를 사용하는거 정도로도 충분히 의미 있는 보안이라고 볼수 있음. 난독화는 지금 안해도 되겠지만 익명함수를 이용하는건 할 필요가 있음. 올려준 링크의 마지막 코드를 참조해서 현재 script.js의 전체 코드를
(function(){
  //코드
})()
요렇게만 감싸줘도 내가 한 방식으로는 조작이 불가능하니 쉽게 막을수 있는건 막는게 좋아요.
항상 이건 불가능하다. 라고 쉽게 말해선 안됩니다.
