### ISSUE TITLE
게임 진행을 논블로킹 방식으로 변경해야함.

### ISSUE THREAD

**Issue by oloslanrete** [oloslanrete/Texas_hold-em#2]
```
async nextPhase(){
        switch(this.game_phase){
            //프리플랍
            case 0:
                if(this.gatherEnty(this.baseEnty)){
                    this.maxBet = this.baseEnty;
                    this.dealingCards();
                    await this.animate_dealing();
                    console.log('end animate')
                    await this.takeActions();
                    this.game_phase++;
                    this.nextPhase();
                }
                break;
            //플랍
            case 1:
                this.flopCards();
                this.animate_flop();
                await this.takeActions();
                this.game_phase++;
                this.nextPhase();
                break;
            //턴
            case 2:
                this.turnCard();
                this.animate_turn();
                await this.takeActions();
                alert('turn end')
                this.game_phase++;
                this.nextPhase();
                break;
            //리버
            case 3:
                this.riverCard();
                this.animate_river();
                await this.takeActions();
                this.endRound();
                break;
        }
    }
```
위 코드의 async await는 자바스크립트의 이벤트 처리 방식의 특성을 잘못 이해하고 작성된 코드이고 필요하지 않은 블로킹io 방식이기 때문에 논블로킹 방식으로 수정이 필요.

**Comment by oloslanrete** [comment]
animation 인터페이스
```
var animator={
    animationQueue: [], //애니메이션 클래스들을 큐 형태로 등록
    newCard: function(id){...}, //애니메이션을 적용할 div를 새로 만듦
    animateNext: function(){...}, //큐에 등록된 가장 첫번째 애니메이션을 빼내서(shift 메소드) 실행
    //각 애니메이션은 duration을 받고 setTimeout을 이용해서 duration이후 콜백으로 animateNext를 실행.
    move: function(div, moveToX, moveToY, duration){...}, //카드를 목적지로 이동시키는 애니메이션
    flip: function(div, cardid, duration){...}, // 카드를 뒤집어서 패를 보여주는 애니메이션
    deleteCard: function(id){...} //만들었던 div가 라운드가 종료되는 등 필요 없어지면 삭제
};

class animation{
    constructor(div, type, duration){ 
        this.div = div //애니메이션을 적용할 html 요소
        this.type = type; //애니메이션 타입. 현재 move, flip이 있음.
        this.duraion = duration; //애니메이션이 지속되는 시간.
        this.args = arguments.slice(3); //위 세가지 외의 요소는  애니메이션마다 필요한 argument가 다르므로 유연하게 적용.
    }
}
```

**Comment by yoonkwon** [comment]
깃헙 코드에서 permalink를 복붙하면 해당 코드를 이슈상에 첨부 가능해서 복붙 안해도 됨
https://docs.github.com/en/github/managing-your-work-on-github/managing-your-work-with-issues-and-pull-requests/creating-a-permanent-link-to-a-code-snippet

https://github.com/oloslanrete/Texas_hold-em/blob/e29128729d5b84a11f0d9540b2b2318896296499/script.js#L248-L278

**Comment by yoonkwon** [comment]
js 이벤트 루프와 비동기 처리에 대해서는 요 [아티클](https://engineering.huiseoul.com/%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%9E%91%EB%8F%99%ED%95%98%EB%8A%94%EA%B0%80-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%EB%A3%A8%ED%94%84%EC%99%80-%EB%B9%84%EB%8F%99%EA%B8%B0-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%EC%9D%98-%EB%B6%80%EC%83%81-async-await%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%BD%94%EB%94%A9-%ED%8C%81-%EB%8B%A4%EC%84%AF-%EA%B0%80%EC%A7%80-df65ffb4e7e) 을 읽어보면 좋을것 같고

비동기 방식으로도 충분히 구현을 할수 있고 2단계로 가면 네트워크 io 를 쓰게 되면 무조건 요구될것이라서 
이벤트 기반으로 구현을 하는게 어떤가 싶음
https://css-tricks.com/lets-create-a-lightweight-native-event-bus-in-javascript/
이런식으로 간단히 이벤트 버스를 구현한것도 있고

**Comment by yoonkwon** [comment]
요는 데이터 변경과 그림 그리는 것을 분리를 하고
two-way data binding 방식으로 되면 이런류의 복잡한 이벤트를 분리해서 구현이 가능함

**Comment by yoonkwon** [comment]
https://github.com/jakesgordon/javascript-state-machine
