### ISSUE TITLE
시각표현 개선

### ISSUE THREAD

**Issue by oloslanrete** [oloslanrete/Texas_hold-em#5]
1. 타 플레이어가 어떤 액션을 취했는지 표시
2. 판돈이 얼마나 걸려있는지 표시
3. 리버 액션 이후 상대 패 공개

**Comment by oloslanrete** [comment]
현재 nonblockio 브랜치가 병합 대기중.
새 폴더에 클론하고 visual이라는 새 브랜치를 만들어 nonblockio와 별개로 진행 예정.

**Comment by oloslanrete** [comment]
상대 패 공개하는 기능 완료.
자료 조사 과정에서 마지막까지 가야 상대패를 확인할 수 있고 중간에 폴드하여 승패가 결정나는 경우 상대 패를 볼 수 없다고 함.
두가지 경우를 분리할 예정.

**Comment by yoonkwon** [comment]
풀리퀘랑 해당작업이 컨플릭이 나는지 보고 난다면 어떻게 머지할수 있을지 확인해봅시다

**Comment by oloslanrete** [comment]
타 플레이어의 액션 표시기능 완료.
판돈 표시 기능 완료.
풀리퀘 예정
