### ISSUE TITLE
패 판별 함수에 버그 발견

### ISSUE THREAD

**Issue by oloslanrete** [oloslanrete/Texas_hold-em#7]
시각 효과 개선 중 패 판별 결과를 띄우면서 발견.
경우의 수가 많아 발견되면 그 때마다 고치고 시각 작업이 끝난 후 테스트 케이스를 만들어 디버깅 예정.

**Comment by yoonkwon** [comment]
경우의 수를 줄일수 있을까요? 족보별로 점수화를 할수 있다면 승패 판정이 좀 더 쉬워질수 있지 않을까요?

**Comment by oloslanrete** [comment]
> 경우의 수를 줄일수 있을까요? 족보별로 점수화를 할수 있다면 승패 판정이 좀 더 쉬워질수 있지 않을까요?

네 현재 족보 판단 함수가 족보별 점수를 먼저 비교하고 같을 경우 더 높은 카드가 있는 쪽이 이기도록 설계가 되어있습니다. 
현재 문제는 입력받은 카드들로부터 가장 높은 점수의 족보를 받지 못하고 있습니다. 
원인을 발견한 뒤 추가적으로 이슈를 등록하도록 하겠습니다.

**Comment by oloslanrete** [comment]
pair, kind를 판별하지 못하는 원인 발견. 카드 오브젝트와 카드의 숫자를 비교하고 있었음. 숫자끼리 비교하도록 수정.
https://github.com/oloslanrete/Texas_hold-em/blob/bce7bb37aa4ca16adf7c284f8af3087945ce3130/script.js#L788-L789

**Comment by oloslanrete** [comment]
pair, kind 리턴값이 정해진 형식에 맞지 않는 문제 발견. 수정함.

**Comment by oloslanrete** [comment]
플러시인 경우 스트레이트 플러시로 판별하는 버그 발견. 수정함.

**Comment by oloslanrete** [comment]
풀하우스를 판별하지 못하는 원인 발견.
https://github.com/oloslanrete/Texas_hold-em/blob/bce7bb37aa4ca16adf7c284f8af3087945ce3130/script.js#L788-L797
랭크가 가장 낮은 패가 여러개 있을 경우 마지막 루프에서 kindlist에 등록되지 못함. 다음루프에서 수가 변경될 때까지 카운트를 올리다가 변경된 뒤에야 등록하는데 가장 낮은 패는 다음에 다른 수가 올 수 없기 때문. 
루프문 밖에서 한번 더 검사하는것으로 수정.
```
for(i=1; i<length; i++){
  if(current.rank == cardlist[i].rank)
      count ++;
  else{
      if(count>1)
          kindlist[count-2].push(current.rank);
      count = 1;
      current = cardlist[i];
  }
}
if(count>1){
  kindlist[count-2].push(current.rank);
  count = 1;
  current = cardlist[i];
}
```
